### ISSUE TITLE
getting Error node-sass & npm rebuild is not working

### ISSUE THREAD

**Issue by 5r1ram** [helloextend/react-challenge#58]
@jakeols 

Could you please help me to resolve it.

**yarn start / yarn run start-dev is not working**

```
mark77@srirams-Air react-challenge % yarn start
yarn run v1.22.19
$ yarn run start-dev
$ webpack-dev-server --config=configs/webpack/dev.js
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/mark77/Downloads/DOx/web/react-challenge
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Note: If you are receiving errors on startup regarding node-sass or image-webpack-loader, try running npm rebuild and then re-running the application.**

**Tried this too! But still not working. I've tried npm rebuild / npx rebuild**

```
mark77@srirams-Air react-challenge % npm rebuild
npm ERR! code 1
npm ERR! path /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/bin/node /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.17.0 | darwin | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:210:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:210:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:210:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:210:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:210:21)
npm ERR! gyp ERR! System Darwin 22.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/mark77/Downloads/DOx/web/react-challenge/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/mark77/Downloads/DOx/web/react-challenge/node_modules/node-sass
npm ERR! gyp ERR! node -v v18.17.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in: /Users/mark77/.npm/_logs/2023-08-30T15_39_14_809Z-debug-0.log
```

**Comment by 5r1ram** [comment]
1. **Node Version Downgrade:**
   I initiated the process by utilizing Node Version Manager (NVM) to install an earlier version of Node.js. Specifically, I selected version 14.15.0 using the command:
   ```
   nvm install 14.15.0
   ```
2. **Project Start:**
   Then, I launched the project by executing the command `yarn start`. If the project's server initialized without any issues and ran smoothly. That's fine. If not followed next step👇.
   
3. **Error Handling - node-sass Issue:**
     Faced ```node-sass``` error, then tried the below command.
   ```
   npm rebuild
   ```
4. **Project Server Restoration:**
   Following the successful execution of `npm rebuild`, I reattempted launching the project server by running `yarn start`  successfully.
